CREATE TABLE IF NOT EXISTS `users` (
  id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  trips int(11) FOREIGN KEY REFERENCES Trip(trip_id),
  likedTrips int(11) FOREIGN KEY REFERENCES Trip(trip_id)
)

CREATE TABLE IF NOT EXISTS `trip` (
  id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
)

CREATE TABLE IF NOT EXISTS `day` (
  id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
)

CREATE TABLE IF NOT EXISTS `review` (
  id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
)

CREATE TABLE IF NOT EXISTS `trailreport` (
  id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
)